Traceback (most recent call last):
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/khuyen/book/venv/lib/python3.8/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from numpy.testing import assert_almost_equal, assert_array_equal

a = np.array([[1.222, 2.222], [3.222, 4.222]])
test = np.array([[1.221, 2.221], [3.221, 4.221]])
assert_almost_equal(a, test, decimal=2)

assert_array_equal(a, test)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_342591/1850860365.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0massert_almost_equal[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mtest[0m[0;34m,[0m [0mdecimal[0m[0;34m=[0m[0;36m2[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;34m[0m[0m
[0;32m----> 7[0;31m [0massert_array_equal[0m[0;34m([0m[0ma[0m[0;34m,[0m [0mtest[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
    [0;31m[... skipping hidden 1 frame][0m

[0;32m~/book/venv/lib/python3.8/site-packages/numpy/testing/_private/utils.py[0m in [0;36massert_array_compare[0;34m(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)[0m
[1;32m    838[0m                                 [0mverbose[0m[0;34m=[0m[0mverbose[0m[0;34m,[0m [0mheader[0m[0;34m=[0m[0mheader[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    839[0m                                 names=('x', 'y'), precision=precision)
[0;32m--> 840[0;31m             [0;32mraise[0m [0mAssertionError[0m[0;34m([0m[0mmsg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    841[0m     [0;32mexcept[0m [0mValueError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    842[0m         [0;32mimport[0m [0mtraceback[0m[0;34m[0m[0;34m[0m[0m

[0;31mAssertionError[0m: 
Arrays are not equal

Mismatched elements: 4 / 4 (100%)
Max absolute difference: 0.001
Max relative difference: 0.000819
 x: array([[1.222, 2.222],
       [3.222, 4.222]])
 y: array([[1.221, 2.221],
       [3.221, 4.221]])
AssertionError: 
Arrays are not equal

Mismatched elements: 4 / 4 (100%)
Max absolute difference: 0.001
Max relative difference: 0.000819
 x: array([[1.222, 2.222],
       [3.222, 4.222]])
 y: array([[1.221, 2.221],
       [3.221, 4.221]])

